name: Decrypt Secrets

inputs:
  ENVIRONMENT_MANAGEMENT:
    required: false
  pagerduty_token:
    required: false
  pagerduty_userapi_token:
    required: false
  slack_webhook_url:
    required: false
  environments:
    required: false
  github_ci_user_pat: 
    required: false
  PASSPHRASE: 
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Decrypt Secrets
      shell: bash
      run: |
        if [ -n "${{ inputs.ENVIRONMENT_MANAGEMENT }}" ]; then
        ENVIRONMENT_MANAGEMENT_DECRYPT=$(gpg --decrypt --quiet --batch --PASSPHRASE "${{ inputs.PASSPHRASE }}" --output - <(echo "${{ inputs.ENVIRONMENT_MANAGEMENT }}" | base64 --decode))
        echo "::add-mask::$ENVIRONMENT_MANAGEMENT_DECRYPT"
        echo "ENVIRONMENT_MANAGEMENT=$environment_management_decrypt" >> $GITHUB_ENV
        fi
        
        if [ -n "${{ inputs.pagerduty_token }}" ]; then
        pagerduty_token_decrypt=$(gpg --decrypt --quiet --batch --PASSPHRASE "${{ inputs.PASSPHRASE }}" --output - <(echo "${{ inputs.pagerduty_token }}" | base64 --decode))
        echo "::add-mask::$pagerduty_token_decrypt"
        echo "TF_VAR_pagerduty_token=$pagerduty_token_decrypt" >> $GITHUB_ENV
        fi
        
        if [ -n "${{ inputs.pagerduty_userapi_token }}" ]; then
        pagerduty_userapi_token_decrypt=$(gpg --decrypt --quiet --batch --PASSPHRASE "${{ inputs.PASSPHRASE }}" --output - <(echo "${{ inputs.pagerduty_userapi_token }}" | base64 --decode))
        echo "::add-mask::$pagerduty_userapi_token_decrypt"
        echo "TF_VAR_pagerduty_user_token=$pagerduty_userapi_token_decrypt" >> $GITHUB_ENV
        fi

        if [ -n "${{ inputs.slack_webhook_url }}" ]; then
        slack_webhook_url_decrypt=$(gpg --decrypt --quiet --batch --PASSPHRASE "${{ inputs.PASSPHRASE }}" --output - <(echo "${{ inputs.slack_webhook_url }}" | base64 --decode))
        echo "::add-mask::$slack_webhook_url_decrypt"
        echo "SLACK_WEBHOOK_URL=$slack_webhook_url_decrypt" >> $GITHUB_ENV
        fi

        if [ -n "${{ inputs.github_ci_user_pat }}" ]; then
        github_ci_user_pat_decrypt=$(gpg --decrypt --quiet --batch --PASSPHRASE "${{ inputs.PASSPHRASE }}" --output - <(echo "${{ inputs.github_ci_user_pat }}" | base64 --decode))
        echo "::add-mask::$github_ci_user_pat_decrypt"
        echo "TF_VAR_github_token=$github_ci_user_pat_decrypt" >> $GITHUB_ENV
        fi
