name: test
on: 
  workflow_dispatch:
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - name: test
          id: plan
          run: |
            exitcode=0
            exitcode=1
            echo "exitcode=${exitcode}" >> $GITHUB_OUTPUT
            (( exitcode == 1 )) && exit 1 || exit 0
        - name: sample
          run: |
            echo ${{ steps.plan.outputs.exitcode }}
